- defaults:
    link:
      relink: true
      create: true

- clean:
    ["~", "~/.config", "~/.local", "~/.local/share", "~/.local/state", "~/bin"]

- link:
    ~/.config/git:
      path: git

    ~/.gitconfig:
      path: ~/.config/git/gitconfig
      force: true

    ~/.config/shell:
      path: shell

    ~/.config/zsh:
      path: zsh

    ~/.zshrc:
      path: zsh/zshrc
      force: true

    ~/.config/bash:
      path: bash

    ~/.bashrc:
      path: bash/bashrc
      force: true

    ~/.config/tmux:
      path: tmux

    ~/.tmux.conf:
      path: tmux/tmux.conf
      force: true

    ~/.config/starship:
      path: starship

    ~/.config/alacritty:
      path: alacritty

    ~/bin:
      path: bin

    ~/.config/nvim:
      path: nvim

    ~/.config/vscode:
      path: vscode

    ~/.vscode/extensions/extensions.json:
      path: vscode/extensions.json
      force: true
- shell:
    - [git submodule update --init --recursive, Installing submodules]
