- defaults:
    link:
      relink: true
      create: true

- clean: ["~", "~/.config"]

- link:
    ~/.config/git:
      path: git

    ~/.gitconfig:
      path: ~/.config/git/gitconfig

    ~/.config/shell:
      path: shell

    ~/.config/zsh:
      path: zsh

    ~/.zshrc:
      path: zsh/zshrc

    ~/.config/bash:
      path: bash

    ~/.bashrc:
      path: bash/bashrc

    ~/.config/tmux:
      path: tmux

    ~/.tmux.conf:
      path: tmux/tmux.conf

    ~/.config/starship:
      path: starship

    ~/.config/alacritty:
      path: alacritty

    ~/bin:
      path: bin

    ~/.config/nvim:
      path: nvim

    ~/.config/vscode:
      path: vscode

    ~/.vscode/extensions/extensions.json:
      path: vscode/extensions.json
- shell:
    - [git submodule update --init --recursive, Installing submodules]
