export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"

# Allow local customizations in the ~/.zshrc_local_before file
if [ -f ~/.zshrc_local_before ]; then
    source ~/.zshrc_local_before
fi

source "$XDG_CONFIG_HOME/shell/settings.sh"
source "$XDG_CONFIG_HOME/shell/functions.sh"
source "$XDG_CONFIG_HOME/shell/bootstrap.sh"
source "$XDG_CONFIG_HOME/shell/aliases.sh"

source "$XDG_CONFIG_HOME/zsh/settings.zsh"

# Allow local customizations in the ~/.zshrc_local_after file
if [ -f ~/.zshrc_local_after ]; then
    source ~/.zshrc_local_after
fi

# Allow private customizations (not checked in to version control)
if [ -f ~/.zshrc_private ]; then
    source ~/.zshrc_private
fi
