export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"

source "$XDG_CONFIG_HOME/shell/settings.sh"
source "$XDG_CONFIG_HOME/shell/functions.sh"
source "$XDG_CONFIG_HOME/shell/bootstrap.sh"
source "$XDG_CONFIG_HOME/shell/aliases.sh"

source "$XDG_CONFIG_HOME/bash/settings.bash"
