export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_STATE_HOME="$HOME/.local/state"

# Allow local customizations in the ~/.bashrc_local_before file
if [ -f ~/.bashrc_local_before ]; then
    source ~/.bashrc_local_before
fi

source "$XDG_CONFIG_HOME/shell/settings.sh"
source "$XDG_CONFIG_HOME/shell/functions.sh"
source "$XDG_CONFIG_HOME/shell/bootstrap.sh"
source "$XDG_CONFIG_HOME/shell/aliases.sh"

source "$XDG_CONFIG_HOME/bash/settings.bash"

# Allow local customizations in the ~/.bashrc_local_after file
if [ -f ~/.bashrc_local_after ]; then
    source ~/.bashrc_local_after
fi

# Allow private customizations (not checked in to version control)
if [ -f ~/.bashrc_private ]; then
    source ~/.bashrc_private
fi
